// Operations service manifest (spec 012, contracts/operations-manifest.md). Grows through the user
// stories: US1 catalog+stock, US2 movements/locations, US3 BOM, US4 writes + order/build/receipt reads,
// US5 costing. Each function is rendered by the 011 FunctionWorkspace and called via the 009 edge.
import type { ReferenceSource, ServiceManifest } from "../types";

// References to the catalog items + locations lists — the pickers + id→label resolution source from here.
const ITEMS_SOURCE: ReferenceSource = {
  path: "/api/operations/items",
  valueKey: "id",
  labelKeys: ["sku", "name"],
};
const LOCATIONS_SOURCE: ReferenceSource = {
  path: "/api/operations/locations",
  valueKey: "id",
  labelKeys: ["code", "name"],
};

/** Resolve item-id + location-id result columns to human labels. */
const stockLabels = [
  { columns: ["itemId"], source: ITEMS_SOURCE },
  { columns: ["locationId"], source: LOCATIONS_SOURCE },
];

export const operationsManifest: ServiceManifest = {
  id: "operations",
  label: "Operations",
  icon: "Package",
  basePath: "/api/operations",
  functions: [
    // --- Catalog ---
    {
      id: "items",
      label: "Items",
      icon: "Package",
      method: "GET",
      path: "/items",
      result: "table",
      description: "Catalog items — sku, name, type, unit, valuation, cost.",
    },
    {
      id: "item",
      label: "Item detail",
      icon: "FileText",
      method: "GET",
      path: "/items/{id}",
      result: "detail",
      inputs: [{ name: "id", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE }],
      description: "Full attributes for one catalog item.",
    },
    // --- Inventory ---
    {
      id: "stock",
      label: "Stock on hand",
      icon: "Boxes",
      method: "GET",
      path: "/items/{id}/availability",
      result: "table",
      inputs: [{ name: "id", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE }],
      resultRefs: stockLabels,
      description: "On-hand / reserved / available per location (the reservations view).",
    },
    {
      id: "movements",
      label: "Movement ledger",
      icon: "ScrollText",
      method: "GET",
      path: "/movements?itemId={itemId}&from={from}&to={to}",
      result: "table",
      inputs: [
        { name: "itemId", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE },
        { name: "from", label: "From", type: "text", placeholder: "ISO datetime (optional)" },
        { name: "to", label: "To", type: "text", placeholder: "ISO datetime (optional)" },
      ],
      resultRefs: stockLabels,
      description: "Stock movements for an item (receipts, issues, transfers, builds).",
    },
    {
      id: "locations",
      label: "Locations",
      icon: "Warehouse",
      method: "GET",
      path: "/locations",
      result: "table",
      description: "Stock locations for this client.",
    },
    // --- BOM ---
    {
      id: "bom-explosion",
      label: "BOM explosion",
      icon: "Network",
      method: "GET",
      path: "/boms/{parentItemId}/explosion?quantity={quantity}",
      result: "table",
      inputs: [
        {
          name: "parentItemId",
          label: "Manufactured item",
          type: "reference",
          required: true,
          source: ITEMS_SOURCE,
        },
        { name: "quantity", label: "Quantity", type: "number", placeholder: "default 1" },
      ],
      resultRefs: [{ columns: ["componentItemId"], source: ITEMS_SOURCE }],
      description: "Flat component requirements for a manufactured item (already exploded + summed).",
    },
    // --- Sales (reads + create/lifecycle) ---
    {
      id: "sales-orders",
      label: "Sales orders",
      icon: "ClipboardList",
      method: "GET",
      path: "/sales-orders",
      result: "table",
      description: "All sales orders with their status.",
    },
    {
      id: "sales-order",
      label: "Sales order detail",
      icon: "FileText",
      method: "GET",
      path: "/sales-orders/{id}",
      result: "detail",
      inputs: [{ name: "id", label: "Sales order id", type: "text", required: true }],
    },
    {
      id: "create-sales-order",
      label: "New sales order",
      icon: "Plus",
      method: "POST",
      path: "/sales-orders",
      result: "detail",
      inputs: [
        { name: "customerRef", label: "Customer reference", type: "text", required: true },
        {
          name: "lines",
          label: "Lines",
          type: "list",
          required: true,
          minRows: 1,
          fields: [
            { name: "itemId", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE },
            { name: "quantity", label: "Quantity", type: "number", required: true },
            { name: "unitPrice", label: "Unit price", type: "number", required: true },
            { name: "uom", label: "Unit", type: "text" },
          ],
        },
      ],
      description: "Create a customer order with one or more lines.",
    },
    {
      id: "confirm-sales-order",
      label: "Confirm sales order",
      icon: "CheckCircle2",
      method: "POST",
      path: "/sales-orders/{id}/confirm",
      result: "detail",
      inputs: [{ name: "id", label: "Sales order id", type: "text", required: true }],
    },
    {
      id: "fulfill-sales-order",
      label: "Fulfill sales order",
      icon: "PackageCheck",
      method: "POST",
      path: "/sales-orders/{id}/fulfill",
      result: "detail",
      inputs: [{ name: "id", label: "Sales order id", type: "text", required: true }],
    },
    {
      id: "cancel-sales-order",
      label: "Cancel sales order",
      icon: "XCircle",
      method: "POST",
      path: "/sales-orders/{id}/cancel",
      result: "detail",
      inputs: [{ name: "id", label: "Sales order id", type: "text", required: true }],
    },
    // --- Production (reads + create) ---
    {
      id: "builds",
      label: "Production builds",
      icon: "Factory",
      method: "GET",
      path: "/builds",
      result: "table",
      resultRefs: [{ columns: ["finishedItemId"], source: ITEMS_SOURCE }],
      description: "All production builds with their status.",
    },
    {
      id: "build",
      label: "Build detail",
      icon: "FileText",
      method: "GET",
      path: "/builds/{id}",
      result: "detail",
      inputs: [{ name: "id", label: "Build id", type: "text", required: true }],
    },
    {
      id: "create-build",
      label: "Production build",
      icon: "Hammer",
      method: "POST",
      path: "/builds",
      result: "detail",
      inputs: [
        {
          name: "finishedItemId",
          label: "Finished item",
          type: "reference",
          required: true,
          source: ITEMS_SOURCE,
        },
        { name: "locationId", label: "Location", type: "reference", required: true, source: LOCATIONS_SOURCE },
        { name: "quantity", label: "Quantity", type: "number", required: true },
      ],
      description: "Consume a manufactured item's components and produce output.",
    },
    // --- Costing ---
    {
      id: "cost",
      label: "Cost & margin",
      icon: "Calculator",
      method: "GET",
      path: "/items/{id}/cost?salePrice={salePrice}",
      result: "detail",
      inputs: [
        { name: "id", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE },
        { name: "salePrice", label: "Sale price", type: "number", placeholder: "optional" },
      ],
      description: "Item unit cost, valuation method, and margin against a sale price.",
    },
    // --- Receiving ---
    {
      id: "receipts",
      label: "Goods receipts",
      icon: "Truck",
      method: "GET",
      path: "/receipts",
      result: "table",
      description: "All goods receipts.",
    },
    {
      id: "receipt",
      label: "Goods receipt detail",
      icon: "FileText",
      method: "GET",
      path: "/receipts/{id}",
      result: "detail",
      inputs: [{ name: "id", label: "Goods receipt id", type: "text", required: true }],
    },
    {
      id: "post-receipt",
      label: "Goods receipt",
      icon: "Truck",
      method: "POST",
      path: "/receipts",
      result: "detail",
      inputs: [
        { name: "supplierRef", label: "Supplier reference", type: "text", required: true },
        { name: "locationId", label: "Location", type: "reference", required: true, source: LOCATIONS_SOURCE },
        {
          name: "lines",
          label: "Lines",
          type: "list",
          required: true,
          minRows: 1,
          fields: [
            { name: "itemId", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE },
            { name: "quantity", label: "Quantity", type: "number", required: true },
            { name: "unitCost", label: "Unit cost", type: "number", required: true },
            { name: "lotCode", label: "Lot code", type: "text" },
            { name: "expiryDate", label: "Expiry date", type: "text" },
            { name: "uom", label: "Unit", type: "text" },
          ],
        },
      ],
      description: "Receive goods from a supplier (posts stock into operations).",
    },
    // --- Catalog writes ---
    {
      id: "create-item",
      label: "New item",
      icon: "PackagePlus",
      method: "POST",
      path: "/items",
      result: "detail",
      inputs: [
        { name: "sku", label: "SKU", type: "text", required: true },
        { name: "name", label: "Name", type: "text", required: true },
        {
          name: "type",
          label: "Type",
          type: "select",
          required: true,
          options: ["RAW_MATERIAL", "COMPONENT", "FINISHED_GOOD", "KIT"],
        },
        { name: "baseUom", label: "Base unit code", type: "text", required: true },
        { name: "valuationMethod", label: "Valuation", type: "select", options: ["AVCO", "FIFO"] },
        { name: "perishable", label: "Perishable", type: "boolean" },
      ],
      description: "Create a catalog item.",
    },
    {
      id: "create-uom",
      label: "New unit of measure",
      icon: "Ruler",
      method: "POST",
      path: "/uoms",
      result: "detail",
      inputs: [
        { name: "code", label: "Code", type: "text", required: true },
        {
          name: "family",
          label: "Family",
          type: "select",
          required: true,
          options: ["MASS", "COUNT", "LENGTH", "VOLUME", "OTHER"],
        },
      ],
      description: "Create a unit of measure.",
    },
    {
      id: "create-conversion",
      label: "New UoM conversion",
      icon: "ArrowLeftRight",
      method: "POST",
      path: "/uom-conversions",
      result: "message",
      inputs: [
        { name: "fromUom", label: "From unit", type: "text", required: true },
        { name: "toUom", label: "To unit", type: "text", required: true },
        { name: "factor", label: "Factor", type: "number", required: true },
      ],
      description: "Define a conversion factor between two units.",
    },
    // --- Inventory writes ---
    {
      id: "create-location",
      label: "New location",
      icon: "MapPin",
      method: "POST",
      path: "/locations",
      result: "detail",
      inputs: [
        { name: "code", label: "Code", type: "text", required: true },
        { name: "name", label: "Name", type: "text", required: true },
      ],
      description: "Create a stock location.",
    },
    {
      id: "post-adjustment",
      label: "Stock adjustment",
      icon: "SlidersHorizontal",
      method: "POST",
      path: "/adjustments",
      result: "detail",
      inputs: [
        { name: "itemId", label: "Item", type: "reference", required: true, source: ITEMS_SOURCE },
        { name: "locationId", label: "Location", type: "reference", required: true, source: LOCATIONS_SOURCE },
        { name: "quantity", label: "Quantity", type: "number", required: true },
        { name: "reason", label: "Reason", type: "text", required: true },
        { name: "uom", label: "Unit", type: "text" },
        { name: "lotId", label: "Lot id", type: "text" },
      ],
      resultRefs: stockLabels,
      description: "Post a signed stock adjustment.",
    },
    // --- BOM write ---
    {
      id: "create-bom",
      label: "New bill of materials",
      icon: "Network",
      method: "POST",
      path: "/boms",
      result: "detail",
      inputs: [
        {
          name: "parentItemId",
          label: "Parent item",
          type: "reference",
          required: true,
          source: ITEMS_SOURCE,
        },
        {
          name: "type",
          label: "Type",
          type: "select",
          required: true,
          options: ["MANUFACTURED", "KIT"],
        },
        { name: "outputQuantity", label: "Output quantity", type: "number", required: true },
        {
          name: "components",
          label: "Components",
          type: "list",
          required: true,
          minRows: 1,
          fields: [
            {
              name: "componentItemId",
              label: "Component",
              type: "reference",
              required: true,
              source: ITEMS_SOURCE,
            },
            { name: "quantity", label: "Quantity", type: "number", required: true },
            { name: "uom", label: "Unit", type: "text" },
          ],
        },
      ],
      description: "Define the component structure of a manufactured item or kit.",
    },
  ],
};
